apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xmrig
  name: xmrig
  namespace: xmrig 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xmrig
  strategy: {}
  template:
    metadata:
      labels:
        app: xmrig
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xmrig
            topologyKey: "kubernetes.io/hostname"
      containers:
      - image: imrealq/xmrig:local
        name: xmrig
        imagePullPolicy: IfNotPresent
        # command: ["./xmrig"]
        # args: ["-c", "config.json"]
        resources:
          limits:
            memory: "3.5Gi"
            cpu: "1"
          requests:
            memory: "1.5Gi"
            cpu: "1"